image: node:10.14

stages:
  - test

lint:
  stage: test
  before_script:
    - npm i
  script:
    - npm run lint
  cache:
    paths:
      - node_modules/

test:
  stage: test
  before_script:
    - npm i
  script:
    - npm run test:ci
  coverage: /All files\s*\|\s*([\d\.]+)/
  cache:
    paths:
      - node_modules/
